apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort # Dit à Minikube d'ouvrir un port externe
  ports:
    - port: 8080      # Le port exposé par le service dans le cluster
      targetPort: 8080 # Le port sur lequel écoute ton conteneur Python
      nodePort: 30080  # Le port fixe sur lequel tu vas te connecter depuis ta machine (choisir entre 30000 et 32767)
  selector:
    app: webapp # Doit correspondre au label 'app: webapp' de tes pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: image-search-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: app-secrets
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_DATABASE
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        volumeMounts:
        - name: torch-cache
          mountPath: /root/.cache/torch
        - name: pip-cache
          mountPath: /root/.cache/pip
      volumes:
      - name: torch-cache
        persistentVolumeClaim:
          claimName: torch-cache
      - name: pip-cache
        persistentVolumeClaim:
          claimName: pip-cache

